export { Home } from './home/Home'
export { Portfolio } from './portfolio/Portfolio'
export { HowToPage } from './howToPage/HowToPage'
export { About } from './about/About'
export { NotFound } from './notFound/NotFound'
