version: "3.4"

services:
  webapp:
    image: yazilimvip/howto-react:latest
    ports:
      - "5100:80"
    environment:
      - "API_URL=http://localhost:5000"
    depends_on:
      - service
  service:
    image: yazilimvip/howto-script:0.10.2
    volumes:
      - /home/maemresen/workspace/yvip/howto/yvip-howto-archive:/usr/src/app/howto
    ports:
      - "5000:5000"
