export { HowToArchive } from './howto'
export { CustomNavbar } from './customNavbar/CustomNavbar'
export { PersonCard } from './personCard/PersonCard'
export { PortfolioCard } from './portfolioCard/PortfolioCard'
export { VipIcon } from './vipIcon/VipIcon'
export { Page } from './page/Page'
export { Cv } from './cv/Cv'
