export { Home } from './home/Home'
export { Portfolio } from './portfolio/Portfolio'
export { HowTo } from './howTo/HowTo'
export { About } from './about/About'
export { NotFound } from './notFound/NotFound'
