name: Docker Image - Build & Publish
on:
  push:
    branches:
      - "main"
jobs:
  docker_image_publish:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: Build and Publish
        run: |
          yarn install
          yarn showcase:webapp:bundle
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
      - uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}
          push: true
          tags: yazilimvip/howto-react:${{ steps.package-version.outputs.current-version}}
