const ON_API_SUCCESS = 'ON_API_SUCCESS'
const ON_API_ERROR = 'ON_API_ERROR'
const ON_SEARCH = 'ON_SEARCH'
const ON_TOGGLE = 'ON_TOGGLE'

export const HOWTO_ACTION_TYPES = {
    ON_API_ERROR,
    ON_API_SUCCESS,
    ON_SEARCH,
    ON_TOGGLE
}
